version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...
  pre_build:
    commands:
      - echo Entered the pre_build phase...
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - sudo docker-compose up --build -d
  post_build:
    commands:
      - echo Entered the post_build phase...
      - sudo docker-compose down --rmi all -v
      - echo Build completed on `date`
